name: Deploy Ansible

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Copier playbook
        run: |
          cp playbook.yml playbook.yml
          cp inventory.ini inventory.ini

      - name: Lancer le playboob
        run: |
            export ANSIBLE_HOST_KEY_CHECKING=False
            ansible-playbook -i inventory.ini playbook.yml