---
- name: Déploiement via SSH
  hosts: serveurs
  become: yes
  tasks:

    - name: Mettre à jour apt
      apt:
        update_cache: yes

    - name: Installer nginx
      apt:
        name: nginx
        state: present

    - name: Démarrer nginx
      service:
        name: nginx
        state: started
        enabled: yes

    - name: Créer page de test
      copy:
        dest: /var/www/html/index.html
        content: "<h1>Déploiement réussi via Ansible SSH !</h1>"