name: Discord Notification

on:
  push:
    branches:
      - dev          # Branche qui déclenche l'action
  workflow_dispatch: # Pour lancement manuel

jobs:
  discord_message:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer requests
        run: pip install requests

      - name: Envoyer message Discord
        run: python script.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
