name: CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      # Étape modifiée pour simuler un échec
      - name: Run tests (simulate fail)
        run: bash scripts/test-fail.sh

      - name: Notify Discord on success
        if: success()
        run: |
          curl -H "Content-Type: application/json" `
               -d "{\"content\": \"✅ Build SUCCESS for $GITHUB_REPOSITORY ($GITHUB_REF)\"}" `
               ${{ secrets.DISCORD_WEBHOOK_URL }}

      - name: Notify Discord on failure
        if: failure()
        run: |
          curl -H "Content-Type: application/json" `
               -d "{\"content\": \"❌ Build FAILED for $GITHUB_REPOSITORY ($GITHUB_REF)\"}" `
               ${{ secrets.DISCORD_WEBHOOK_URL }}