name: Deploy Ansible

# Déclenchement manuel
on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # ton runner auto-hébergé
    steps:
      # Récupérer le dépôt
      - uses: actions/checkout@v3

      # Désactiver la vérification de clé SSH pour éviter les erreurs
      - name: Lancer le playbook Ansible
        run: |
          export ANSIBLE_HOST_KEY_CHECKING=False
          ansible-playbook -i inventory.ini playbook.yml
