name: Envoi de message Discord

on:
  push:
    branches-ignore:
      - main

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: Ne rien faire
        run: echo "Workflow désactivé sur main"
